### ISSUE TITLE
Adapt `pyserved` to Choam

### ISSUE THREAD

**Issue by cowboycodr** [SblipDev/pyserved#2]
[Choam](https://github.com/cowboycodr/choam) will allow for faster speed of development. 

To simulate the adaption:
- have `choam` installed
- be in pyserved directory
- run `$ choam init --adapt`
- confirm files you want to move
- dont

**Comment by shaurya-blip** [comment]
Seems nice. Lemme check your PR.

**Comment by shaurya-blip** [comment]
Merged PR. Thank you!
